spring:
  application:
    name: UzAirWays

  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:5433/uz_air_ways
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  #servlet:
  #  context-path: /api/v1
