name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Spring application
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build Spring Boot application using Gradle
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      # Step 4: Set up Docker build environment
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Define the VERSION environment variable
      - name: Set Docker image version
        run: echo "VERSION=35" >> $GITHUB_ENV

      # Step 7: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/uz_air_ways:${{ env.VERSION }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/uz_air_ways:${{ env.VERSION }}

      # Step 8: Tag and push Docker image as latest
      - name: Push Docker image as latest
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/uz_air_ways:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/uz_air_ways:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/uz_air_ways:latest

      # Step 9: Show Docker images for debugging
      - name: Show Docker images
        run: docker images
